import {
  Project,
  BuildingProject,
  BuilderProfile,
  CityData,
  ThreadData,
  CUSTOM_EMOJIS,
} from "@/types";

export const seedProjects: Project[] = [
  {
    id: 1,
    name: "Nexus AI",
    tagline: "AI copilot for founder-market fit validation",
    description:
      "Nexus AI combines government economic data, competitor intelligence, and AI analysis to give founders a scored assessment of their market fit. Paste your idea, get a structured report with TAM estimates, competitor mapping, moat analysis, and a viability score grounded in real data.",
    builder: {
      name: "Arjun Mehta",
      avatar: "AM",
      city: "Bangalore",
      title: "Ex-Growth Lead",
      company: "Meesho",
      companyColor: "#F43397",
    },
    collabs: [
      {
        avatar: "PS",
        name: "Priya Shah",
        title: "SDE II",
        company: "Flipkart",
        companyColor: "#F7D03E",
      },
    ],
    weighted: 2847,
    raw: 412,
    category: "AI",
    stack: ["Next.js", "Claude API", "Supabase", "Vercel"],
    buildathon: "The Great Indian AI \u00B7 Week 2",
    heroColor: "#1a1a2e",
    featured: true,
    date: "3 Feb 2026",
    gallery: [
      { type: "screenshot", label: "Dashboard", colors: ["#1a1a2e", "#2d2b55", "#4834d4"] },
      { type: "screenshot", label: "Market analysis report", colors: ["#0a2540", "#1a3a5c", "#2563eb"] },
      { type: "screenshot", label: "Competitor mapping", colors: ["#1b2838", "#2d4a5c", "#3b82f6"] },
    ],
  },
  {
    id: 2,
    name: "PayLoop",
    tagline: "Recurring payments for India's subscription economy",
    description:
      "A payment infrastructure layer that handles recurring billing, dunning, and subscription lifecycle for Indian businesses. Integrates with Razorpay and supports UPI autopay, cards, and net banking.",
    builder: {
      name: "Kavya Iyer",
      avatar: "KI",
      city: "Mumbai",
      title: "PM",
      company: "Razorpay",
      companyColor: "#0C2451",
    },
    collabs: [],
    weighted: 2134,
    raw: 387,
    category: "Fintech",
    stack: ["React", "Node.js", "Razorpay", "PostgreSQL"],
    buildathon: null,
    heroColor: "#0a2540",
    featured: false,
    date: "28 Jan 2026",
    gallery: [
      { type: "screenshot", label: "Payment dashboard", colors: ["#0a2540", "#163b5c", "#1e5a8a"] },
      { type: "screenshot", label: "Subscription flow", colors: ["#1a1a3e", "#2a2a5e", "#3a3a7e"] },
    ],
  },
  {
    id: 3,
    name: "Draftly",
    tagline: "Turn voice notes into publish-ready newsletters",
    description:
      "Record a voice note, Draftly transcribes it, structures it into a newsletter format, matches your writing style from past editions, and gives you a ready-to-send draft. Integrates with Substack and Beehiiv.",
    builder: {
      name: "Rohan Desai",
      avatar: "RD",
      city: "Pune",
      title: "Content Lead",
      company: "Zerodha",
      companyColor: "#387ED1",
    },
    collabs: [
      {
        avatar: "MN",
        name: "Meera Nair",
        title: "Brand Manager",
        company: "Mamaearth",
        companyColor: "#2D7A3F",
      },
    ],
    weighted: 1876,
    raw: 298,
    category: "Content",
    stack: ["Python", "Whisper", "GPT-4", "FastAPI"],
    buildathon: "The Great Indian AI \u00B7 Week 1",
    heroColor: "#1b4332",
    featured: false,
    date: "20 Jan 2026",
    gallery: [
      { type: "screenshot", label: "Voice recording", colors: ["#1b4332", "#2d6a4f", "#40916c"] },
      { type: "screenshot", label: "Draft editor", colors: ["#1b2a1b", "#2d4a2d", "#3d6a3d"] },
    ],
  },
  {
    id: 4,
    name: "HireSignal",
    tagline: "Predict candidate success from behavioural signals",
    description:
      "Analyses video interviews and written assessments using behavioural science models to predict on-the-job performance. Gives hiring managers a structured score alongside traditional resume screening.",
    builder: {
      name: "Ananya Rao",
      avatar: "AR",
      city: "Hyderabad",
      title: "People Ops Lead",
      company: "Swiggy",
      companyColor: "#FC8019",
    },
    collabs: [],
    weighted: 1543,
    raw: 234,
    category: "HR Tech",
    stack: ["Python", "TensorFlow", "React", "FastAPI"],
    buildathon: null,
    heroColor: "#312e81",
    featured: false,
    date: "15 Jan 2026",
    gallery: [],
  },
  {
    id: 5,
    name: "LocaLoop",
    tagline: "Hyperlocal delivery ops for D2C brands",
    description:
      "Plug-and-play delivery orchestration for D2C brands doing same-day delivery. Route optimization, rider allocation, and real-time tracking. Works with existing rider fleets or connects to Dunzo/Porter.",
    builder: {
      name: "Vikram Singh",
      avatar: "VS",
      city: "Delhi NCR",
      title: "Ops Manager",
      company: "Delhivery",
      companyColor: "#E41E26",
    },
    collabs: [
      {
        avatar: "SG",
        name: "Sonal Grover",
        title: "SDE",
        company: "Zomato",
        companyColor: "#E23744",
      },
      {
        avatar: "AK",
        name: "Amit Kumar",
        title: "Designer",
        company: "CRED",
        companyColor: "#1B1B1B",
      },
    ],
    weighted: 1298,
    raw: 201,
    category: "Logistics",
    stack: ["Flutter", "Firebase", "Google Maps API"],
    buildathon: null,
    heroColor: "#7c2d12",
    featured: false,
    date: "8 Jan 2026",
    gallery: [
      { type: "screenshot", label: "Route optimization", colors: ["#7c2d12", "#b45309", "#d97706"] },
      { type: "screenshot", label: "Tracking view", colors: ["#78350f", "#92400e", "#b45309"] },
    ],
  },
  {
    id: 6,
    name: "Luma Health",
    tagline: "AI triage for tier-2 city clinics",
    description:
      "Patients describe symptoms via WhatsApp. Luma uses a medically validated triage model to prioritize cases, suggest preliminary assessments, and route to the right specialist. Built for clinics with 1-3 doctors.",
    builder: {
      name: "Sneha Gupta",
      avatar: "SG",
      city: "Jaipur",
      title: "Clinical Data Analyst",
      company: "Practo",
      companyColor: "#E8384F",
    },
    collabs: [],
    weighted: 987,
    raw: 156,
    category: "Health",
    stack: ["React Native", "FastAPI", "WhatsApp Business API"],
    buildathon: "The Great Indian AI \u00B7 Week 3",
    heroColor: "#064E3B",
    featured: false,
    date: "5 Jan 2026",
    gallery: [],
  },
];

export const seedBuilding: BuildingProject[] = [
  {
    id: 101,
    name: "Stackform",
    tagline: "No-code form builder with conditional logic",
    builder: { name: "Nisha Patel", avatar: "NP", role: "member", city: "Ahmedabad" },
    status: "prototyping",
    watchers: 89,
    log: "Added Stripe integration. Took 4 hours. Broke twice.",
    logDate: "11 Feb 2026",
    help: "Looking for someone who knows Supabase auth",
  },
  {
    id: 102,
    name: "CampusMatch",
    tagline: "Roommate matching for Indian university hostels",
    builder: { name: "Dev Sharma", avatar: "DS", role: "member", city: "Jaipur" },
    status: "idea",
    watchers: 45,
    log: "Interviewed 30 students. Pain point is real. Starting wireframes.",
    logDate: "10 Feb 2026",
    help: null,
  },
  {
    id: 103,
    name: "MetricPulse",
    tagline: "Real-time SaaS dashboard from Stripe + analytics",
    builder: { name: "Tara Menon", avatar: "TM", role: "builder", city: "Kochi" },
    status: "beta",
    watchers: 203,
    log: "Beta live with 12 users. NPS is 72. Fixing mobile layout this weekend.",
    logDate: "12 Feb 2026",
    help: "Need a designer for the dashboard cards",
  },
  {
    id: 104,
    name: "Dhaba",
    tagline: "WhatsApp ordering for neighbourhood restaurants",
    builder: { name: "Amit Patel", avatar: "AP", role: "member", city: "Pune" },
    status: "prototyping",
    watchers: 127,
    log: "WhatsApp Business API approved. Building the menu parser now.",
    logDate: "11 Feb 2026",
    help: "Need someone who's integrated WhatsApp Business API before",
  },
];

export const seedBuilders: BuilderProfile[] = [
  { name: "Arjun Mehta", avatar: "AM", role: "builder", city: "Bangalore", rep: 847, shipped: 4, bio: "AI tools for founders. Ex-Flipkart eng." },
  { name: "Kavya Iyer", avatar: "KI", role: "builder", city: "Mumbai", rep: 623, shipped: 3, bio: "Payments infra. Razorpay alumni." },
  { name: "Tara Menon", avatar: "TM", role: "builder", city: "Kochi", rep: 567, shipped: 2, bio: "Analytics nerd. Data tells stories." },
  { name: "Priya Shah", avatar: "PS", role: "builder", city: "Bangalore", rep: 534, shipped: 3, bio: "Full-stack builder. React + Python." },
  { name: "Rohan Desai", avatar: "RD", role: "founder", city: "Pune", rep: 534, shipped: 2, bio: "Content tools. Building Draftly." },
  { name: "Ananya Rao", avatar: "AR", role: "builder", city: "Hyderabad", rep: 412, shipped: 2, bio: "ML engineer. HR tech obsessed." },
  { name: "Vikram Singh", avatar: "VS", role: "founder", city: "Delhi NCR", rep: 389, shipped: 1, bio: "Logistics + D2C. Building LocaLoop." },
  { name: "Sneha Gupta", avatar: "SG", role: "builder", city: "Jaipur", rep: 345, shipped: 1, bio: "Health tech. Making care accessible." },
  { name: "Nisha Patel", avatar: "NP", role: "member", city: "Ahmedabad", rep: 234, shipped: 0, bio: "PM by day. Building Stackform." },
  { name: "Dev Sharma", avatar: "DS", role: "member", city: "Jaipur", rep: 178, shipped: 0, bio: "EdTech. Understanding campus life." },
];

export const seedCities: CityData[] = [
  { name: "Bangalore", builders: 1203, shipped: 412, flag: "\uD83D\uDFE2", trend: "+48 this month" },
  { name: "Mumbai", builders: 842, shipped: 234, flag: "\uD83D\uDD34", trend: "+31 this month" },
  { name: "Delhi NCR", builders: 567, shipped: 178, flag: "\uD83D\uDFE1", trend: "+22 this month" },
  { name: "Hyderabad", builders: 389, shipped: 134, flag: "\uD83D\uDD35", trend: "+19 this month" },
  { name: "Pune", builders: 312, shipped: 98, flag: "\uD83D\uDFE0", trend: "+14 this month" },
  { name: "Chennai", builders: 278, shipped: 87, flag: "\uD83D\uDFE3", trend: "+11 this month" },
  { name: "Kolkata", builders: 156, shipped: 45, flag: "\u26AA", trend: "+8 this month" },
  { name: "Ahmedabad", builders: 134, shipped: 41, flag: "\uD83D\uDD36", trend: "+6 this month" },
  { name: "Jaipur", builders: 98, shipped: 29, flag: "\uD83E\uDE77", trend: "+5 this month" },
  { name: "Kochi", builders: 87, shipped: 23, flag: "\uD83E\uDE75", trend: "+4 this month" },
  { name: "Chandigarh", builders: 67, shipped: 18, flag: "\uD83D\uDFE4", trend: "+3 this month" },
];

const E = CUSTOM_EMOJIS;

export const seedThreads: ThreadData[] = [
  {
    id: "t1",
    author: {
      name: "Siddharth Nair",
      avatar: "SN",
      role: "builder",
      rep: 723,
      title: "PM",
      company: "Razorpay",
      companyColor: "#0C2451",
    },
    content:
      "How are you handling hallucinations in the market-fit scoring? I built something similar and the AI kept inflating TAM estimates by 3-4x.",
    time: "2 hours ago",
    reactions: [
      { emoji: E[0], count: 4 },
      { emoji: E[3], count: 2 },
      { emoji: E[6], count: 1, mine: false },
    ],
    replies: [
      {
        author: {
          name: "Arjun Mehta",
          avatar: "AM",
          role: "builder",
          isCreator: true,
          title: "Founder",
          company: "Nexus AI",
          companyColor: "#1a1a2e",
        },
        content:
          "Great question. We use a three-layer approach: (1) ground every estimate in government census data and RBI reports, (2) force the model to show its math with citations, (3) run a separate validation pass that flags any number more than 2 standard deviations from the source data. Hallucination rate dropped from ~18% to under 3%.",
        time: "1 hour ago",
        reactions: [
          { emoji: E[5], count: 8 },
          { emoji: E[6], count: 3, mine: false },
        ],
      },
      {
        author: {
          name: "Priya Shah",
          avatar: "PS",
          role: "builder",
          title: "SDE II",
          company: "Flipkart",
          companyColor: "#F7D03E",
        },
        content:
          "The validation pass is the key insight here. We tried a similar approach at my last startup but skipped step 3 and it was unusable in production.",
        time: "45 min ago",
        reactions: [{ emoji: E[4], count: 1 }],
      },
    ],
  },
  {
    id: "t2",
    author: {
      name: "Kavya Iyer",
      avatar: "KI",
      role: "builder",
      rep: 623,
      title: "Founder",
      company: "PayLoop",
      companyColor: "#0a2540",
    },
    content:
      "What's the pricing model going to be? This feels like it could be a premium tool for VCs doing due diligence, not just solo founders.",
    time: "5 hours ago",
    reactions: [
      { emoji: E[1], count: 4 },
      { emoji: E[7], count: 1 },
    ],
    replies: [
      {
        author: {
          name: "Arjun Mehta",
          avatar: "AM",
          role: "builder",
          isCreator: true,
          title: "Founder",
          company: "Nexus AI",
          companyColor: "#1a1a2e",
        },
        content:
          "Starting freemium: 3 validations/month free, unlimited at \u20B92,999/mo. But you're right about the VC angle. Two funds reached out already. Might build a separate tier for institutional use with bulk analysis and portfolio-level insights.",
        time: "4 hours ago",
        reactions: [
          { emoji: E[3], count: 2 },
          { emoji: E[8], count: 2 },
        ],
      },
    ],
  },
  {
    id: "t3",
    author: {
      name: "Meera Nair",
      avatar: "MN",
      role: "member",
      rep: 198,
      title: "Brand Manager",
      company: "Mamaearth",
      companyColor: "#2D7A3F",
    },
    content:
      "Tested this with my D2C snack brand idea. The competitor mapping found 3 brands I'd never heard of. One concern: moat analysis section felt generic. Could it pull in patent data or trademark filings?",
    time: "8 hours ago",
    reactions: [
      { emoji: E[3], count: 2 },
      { emoji: E[9], count: 3 },
    ],
    replies: [],
  },
  {
    id: "t4",
    author: {
      name: "Vikram Singh",
      avatar: "VS",
      role: "founder",
      rep: 389,
      title: "Founder",
      company: "LocaLoop",
      companyColor: "#7c2d12",
    },
    content:
      "Can you add a compare-two-markets mode? I'm torn between logistics and grocery delivery and would love to run them side by side instead of doing two separate analyses.",
    time: "12 hours ago",
    reactions: [
      { emoji: E[0], count: 6 },
      { emoji: E[11], count: 2 },
    ],
    replies: [],
  },
];
