import { Event, Project, Member, Vote, Comment } from "@/types";

export const seedMembers: Member[] = [
  {
    _id: "m1",
    name: "Arjun Mehta",
    avatar: "",
    company: "ContextPilot",
    city: "Bangalore",
    role: "builder",
    bio: "Full-stack dev building AI tools. Shipped 4 products at GrowthX buildathons.",
    linkedIn: "https://linkedin.com/in/arjunmehta",
    twitter: "https://twitter.com/arjunmehta",
    builderScore: 847,
    projectsShipped: 4,
    totalWeightedVotes: 312,
  },
  {
    _id: "m2",
    name: "Priya Sharma",
    avatar: "",
    company: "ShipFast Labs",
    city: "Delhi",
    role: "builder",
    bio: "Product designer turned builder. Making developer tools that don't suck.",
    linkedIn: "https://linkedin.com/in/priyasharma",
    twitter: "https://twitter.com/priyasharma",
    builderScore: 723,
    projectsShipped: 3,
    totalWeightedVotes: 267,
  },
  {
    _id: "m3",
    name: "Rahul Verma",
    avatar: "",
    company: "GrowthX",
    city: "Bangalore",
    role: "host",
    bio: "Community lead at GrowthX Bangalore. Organized 15+ buildathons.",
    linkedIn: "https://linkedin.com/in/rahulverma",
    twitter: "https://twitter.com/rahulverma",
    builderScore: 456,
    projectsShipped: 1,
    totalWeightedVotes: 89,
  },
  {
    _id: "m4",
    name: "Sneha Iyer",
    avatar: "",
    company: "NeuralDocs",
    city: "Pune",
    role: "builder",
    bio: "AI researcher shipping real products. NLP specialist.",
    linkedIn: "https://linkedin.com/in/snehaiyer",
    twitter: "https://twitter.com/snehaiyer",
    builderScore: 612,
    projectsShipped: 2,
    totalWeightedVotes: 198,
  },
  {
    _id: "m5",
    name: "Karan Patel",
    avatar: "",
    company: "QuickLaunch",
    city: "Hyderabad",
    role: "founder",
    bio: "Serial founder. Building tools to help others ship faster.",
    linkedIn: "https://linkedin.com/in/karanpatel",
    twitter: "https://twitter.com/karanpatel",
    builderScore: 534,
    projectsShipped: 3,
    totalWeightedVotes: 178,
  },
  {
    _id: "m6",
    name: "Ananya Reddy",
    avatar: "",
    company: "BuildKit",
    city: "Bangalore",
    role: "builder",
    bio: "Frontend engineer obsessed with great UX. React & Next.js specialist.",
    linkedIn: "https://linkedin.com/in/ananyareddy",
    twitter: "https://twitter.com/ananyareddy",
    builderScore: 489,
    projectsShipped: 2,
    totalWeightedVotes: 156,
  },
  {
    _id: "m7",
    name: "Vikram Singh",
    avatar: "",
    company: "DevFlow",
    city: "Delhi",
    role: "builder",
    bio: "Backend engineer. Building developer infrastructure tools.",
    linkedIn: "https://linkedin.com/in/vikramsingh",
    twitter: "https://twitter.com/vikramsingh",
    builderScore: 398,
    projectsShipped: 2,
    totalWeightedVotes: 134,
  },
  {
    _id: "m8",
    name: "Deepa Nair",
    avatar: "",
    company: "GrowthX",
    city: "Pune",
    role: "host",
    bio: "GrowthX Pune chapter lead. Passionate about fostering builder communities.",
    linkedIn: "https://linkedin.com/in/deepanair",
    twitter: "https://twitter.com/deepanair",
    builderScore: 234,
    projectsShipped: 0,
    totalWeightedVotes: 45,
  },
  {
    _id: "m9",
    name: "Rohan Gupta",
    avatar: "",
    company: "PixelStack",
    city: "Hyderabad",
    role: "member",
    bio: "Product manager exploring the builder side. Learning to ship.",
    linkedIn: "https://linkedin.com/in/rohangupta",
    twitter: "https://twitter.com/rohangupta",
    builderScore: 120,
    projectsShipped: 0,
    totalWeightedVotes: 23,
  },
  {
    _id: "m10",
    name: "Meera Krishnan",
    avatar: "",
    company: "CodeCraft",
    city: "Bangalore",
    role: "builder",
    bio: "Full-stack developer. Loves building Chrome extensions and dev tools.",
    linkedIn: "https://linkedin.com/in/meerakrishnan",
    twitter: "https://twitter.com/meerakrishnan",
    builderScore: 567,
    projectsShipped: 3,
    totalWeightedVotes: 201,
  },
  {
    _id: "m11",
    name: "Aditya Joshi",
    avatar: "",
    company: "LaunchPad",
    city: "Delhi",
    role: "founder",
    bio: "Building LaunchPad - helping startups get their first 100 users.",
    linkedIn: "https://linkedin.com/in/adityajoshi",
    twitter: "https://twitter.com/adityajoshi",
    builderScore: 445,
    projectsShipped: 2,
    totalWeightedVotes: 167,
  },
  {
    _id: "m12",
    name: "Nisha Agarwal",
    avatar: "",
    company: "DataWeave",
    city: "Pune",
    role: "builder",
    bio: "Data engineer building analytics tools. Python and Go enthusiast.",
    linkedIn: "https://linkedin.com/in/nishaagarwal",
    twitter: "https://twitter.com/nishaagarwal",
    builderScore: 378,
    projectsShipped: 2,
    totalWeightedVotes: 145,
  },
];

export const seedEvents: Event[] = [
  {
    _id: "e1",
    name: "Bangalore Buildathon #12",
    type: "buildathon",
    city: "Bangalore",
    date: "2026-02-01",
    host: { memberId: "m3", name: "Rahul Verma" },
    projectCount: 8,
    color: "#FF6B35",
  },
  {
    _id: "e2",
    name: "Delhi AI Hackathon",
    type: "buildathon",
    city: "Delhi",
    date: "2026-01-25",
    host: { memberId: "m7", name: "Vikram Singh" },
    projectCount: 6,
    color: "#7C3AED",
  },
  {
    _id: "e3",
    name: "The Great Indian AI Batch 1",
    type: "cohort",
    city: "Bangalore",
    date: "2026-01-15",
    host: { memberId: "m3", name: "Rahul Verma" },
    projectCount: 5,
    color: "#059669",
  },
  {
    _id: "e4",
    name: "Pune Builder Weekend",
    type: "buildathon",
    city: "Pune",
    date: "2026-01-18",
    host: { memberId: "m8", name: "Deepa Nair" },
    projectCount: 4,
    color: "#2563EB",
  },
  {
    _id: "e5",
    name: "Hyderabad Ship-It Sprint",
    type: "buildathon",
    city: "Hyderabad",
    date: "2026-02-08",
    host: { memberId: "m5", name: "Karan Patel" },
    projectCount: 5,
    color: "#DC2626",
  },
  {
    _id: "e6",
    name: "Community",
    type: "independent",
    city: "All Cities",
    date: "2026-01-01",
    host: { memberId: "m3", name: "Rahul Verma" },
    projectCount: 1,
    color: "#8899AA",
  },
  {
    _id: "e7",
    name: "GrowthX Host Club Bangalore",
    type: "host_club",
    city: "Bangalore",
    date: "2026-01-28",
    host: { memberId: "m3", name: "Rahul Verma" },
    projectCount: 3,
    color: "#F59E0B",
  },
];

export const seedProjects: Project[] = [
  {
    _id: "p1",
    name: "ContextPilot",
    tagline: "AI copilot that understands your entire codebase context",
    description:
      "ContextPilot indexes your entire repository and provides contextual AI assistance that actually understands your architecture, patterns, and business logic. Unlike generic AI tools, it builds a knowledge graph of your codebase.",
    buildLog:
      "Started this at Bangalore Buildathon #12. The idea came from frustration with AI tools that give generic answers. Built the indexing pipeline first using tree-sitter for AST parsing, then layered RAG on top with a custom embedding model fine-tuned on code. The hardest part was handling monorepos with mixed languages. Got the MVP working in 8 hours, then spent the next week polishing the VS Code extension.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://contextpilot.dev",
    category: "AI tool",
    event: "e1",
    cohortTag: "",
    team: [
      { memberId: "m1", name: "Arjun Mehta", avatar: "", role: "Lead Developer" },
      { memberId: "m6", name: "Ananya Reddy", avatar: "", role: "Frontend" },
    ],
    weekSubmitted: 5,
    submittedAt: "2026-02-01T10:00:00Z",
    weightedScore: 142,
    rawVotes: 38,
    traction: { users: "2.1K GitHub stars", revenue: "Pre-revenue" },
  },
  {
    _id: "p2",
    name: "ShipLog",
    tagline: "Build in public with structured shipping logs",
    description:
      "ShipLog helps indie hackers and builders document their journey with structured build logs. Auto-generates changelog from git commits, integrates with Twitter for build-in-public threads, and creates a beautiful public page for your project.",
    buildLog:
      "Built this because I wanted a better way to share what I'm building. Existing tools are either too complex (Notion) or too simple (Twitter threads). Started with the git integration, used GitHub webhooks to auto-generate daily summaries. The Twitter thread generator was the killer feature that got early traction.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://shiplog.io",
    category: "SaaS",
    event: "e1",
    team: [
      { memberId: "m2", name: "Priya Sharma", avatar: "", role: "Solo Builder" },
    ],
    weekSubmitted: 5,
    submittedAt: "2026-02-01T11:00:00Z",
    weightedScore: 118,
    rawVotes: 31,
    traction: { users: 450, revenue: "$2,100 MRR" },
  },
  {
    _id: "p3",
    name: "NeuralDocs",
    tagline: "Turn any documentation into an AI-powered knowledge base",
    description:
      "NeuralDocs ingests your documentation (Notion, Confluence, Google Docs) and creates an intelligent Q&A system for your team. Supports follow-up questions, cites sources, and learns from feedback.",
    buildLog:
      "This started as a cohort project in The Great Indian AI Batch 1. We were tired of searching through hundreds of Notion pages. The core challenge was handling different doc formats and maintaining context across long documents. Used chunking strategies from recent research papers. The Slack bot integration was the feature that made it stick with teams.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://neuraldocs.ai",
    category: "AI tool",
    event: "e3",
    cohortTag: "The Great Indian AI Batch 1",
    team: [
      { memberId: "m4", name: "Sneha Iyer", avatar: "", role: "AI/ML Lead" },
      { memberId: "m12", name: "Nisha Agarwal", avatar: "", role: "Backend" },
    ],
    weekSubmitted: 3,
    submittedAt: "2026-01-15T09:00:00Z",
    weightedScore: 108,
    rawVotes: 28,
    traction: { users: "1.2K active users", revenue: "$890 MRR" },
  },
  {
    _id: "p4",
    name: "QuickLaunch",
    tagline: "Landing page builder that ships in 10 minutes",
    description:
      "QuickLaunch generates conversion-optimized landing pages from a brief description. Uses AI to write copy, select layouts, and generate images. One-click deploy to Vercel or Netlify.",
    buildLog:
      "Started at Delhi AI Hackathon. The insight was that most builders spend days on landing pages when they should be building product. We prompt-engineered GPT-4 to generate entire landing page components, then built a visual editor on top. The 10-minute promise was our north star - if any flow took longer, we simplified it.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://quicklaunch.app",
    category: "SaaS",
    event: "e2",
    team: [
      { memberId: "m5", name: "Karan Patel", avatar: "", role: "Founder" },
      { memberId: "m7", name: "Vikram Singh", avatar: "", role: "Full Stack" },
    ],
    weekSubmitted: 4,
    submittedAt: "2026-01-25T10:00:00Z",
    weightedScore: 95,
    rawVotes: 26,
    traction: { users: 780, revenue: "$1,400 MRR" },
  },
  {
    _id: "p5",
    name: "DevFlow",
    tagline: "Visual workflow builder for developer pipelines",
    description:
      "DevFlow lets you build CI/CD pipelines, data pipelines, and automation workflows with a visual drag-and-drop interface. Generates clean YAML configs for GitHub Actions, GitLab CI, and Jenkins.",
    buildLog:
      "Nobody likes writing YAML. That was the starting point. Built this at Delhi AI Hackathon. The drag-and-drop editor uses React Flow. The tricky part was mapping visual nodes to valid YAML that actually works. We maintain a library of tested pipeline templates that ensure generated configs are production-ready.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://devflow.tools",
    category: "Developer tool",
    event: "e2",
    team: [
      { memberId: "m7", name: "Vikram Singh", avatar: "", role: "Lead" },
      { memberId: "m11", name: "Aditya Joshi", avatar: "", role: "Product" },
    ],
    weekSubmitted: 4,
    submittedAt: "2026-01-25T12:00:00Z",
    weightedScore: 87,
    rawVotes: 24,
    traction: { users: "560 GitHub stars", revenue: "Pre-revenue" },
  },
  {
    _id: "p6",
    name: "BuildKit",
    tagline: "Component library with built-in analytics tracking",
    description:
      "BuildKit is a React component library where every component has built-in analytics. Track button clicks, form completions, page views - all without writing a single line of tracking code. Privacy-first, GDPR compliant.",
    buildLog:
      "Built at Pune Builder Weekend. The idea came from seeing how much time teams spend adding analytics to every UI element. What if the components just tracked themselves? Used a custom React context provider that batches events. The hardest part was making it zero-config while still flexible enough for power users.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://buildkit.dev",
    category: "Developer tool",
    event: "e4",
    team: [
      { memberId: "m6", name: "Ananya Reddy", avatar: "", role: "Creator" },
    ],
    weekSubmitted: 3,
    submittedAt: "2026-01-18T10:00:00Z",
    weightedScore: 76,
    rawVotes: 21,
    traction: { users: "340 npm downloads/week", revenue: "Pre-revenue" },
  },
  {
    _id: "p7",
    name: "CodeSnap",
    tagline: "Beautiful code screenshots with one keyboard shortcut",
    description:
      "CodeSnap is a Chrome extension that captures code from any website (GitHub, StackOverflow, docs) and creates beautiful, shareable screenshots. Supports custom themes, fonts, and watermarks.",
    buildLog:
      "Built this independently because I was tired of using carbon.sh every time. The Chrome extension captures the DOM, applies syntax highlighting, and renders to canvas. Added VS Code theme support so screenshots match your editor. The one-shortcut workflow was key to adoption.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://codesnap.dev",
    category: "Chrome extension",
    event: undefined,
    team: [
      { memberId: "m10", name: "Meera Krishnan", avatar: "", role: "Solo Builder" },
    ],
    weekSubmitted: 4,
    submittedAt: "2026-01-20T14:00:00Z",
    weightedScore: 71,
    rawVotes: 19,
    traction: { users: "4.2K Chrome users", revenue: "Pre-revenue" },
  },
  {
    _id: "p8",
    name: "PipelineHQ",
    tagline: "Sales pipeline for indie hackers and solo founders",
    description:
      "PipelineHQ is a dead-simple CRM designed for people who hate CRMs. Track leads, deals, and follow-ups with a Kanban board. Integrates with email and Twitter DMs. No enterprise bloat.",
    buildLog:
      "Built at Hyderabad Ship-It Sprint. Every CRM is built for sales teams of 50+. We built one for teams of 1-3. Stripped everything down to: contacts, deals, and tasks. The email integration auto-creates contacts and logs conversations. Twitter DM tracking was a unique differentiator.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://pipelinehq.io",
    category: "SaaS",
    event: "e5",
    team: [
      { memberId: "m5", name: "Karan Patel", avatar: "", role: "Product" },
      { memberId: "m9", name: "Rohan Gupta", avatar: "", role: "Design" },
    ],
    weekSubmitted: 6,
    submittedAt: "2026-02-08T10:00:00Z",
    weightedScore: 64,
    rawVotes: 18,
    traction: { users: 120, revenue: "$340 MRR" },
  },
  {
    _id: "p9",
    name: "FormCraft",
    tagline: "AI-powered form builder that writes its own validation",
    description:
      "Describe your form in plain English and FormCraft generates it with proper validation, error messages, and submission handling. Supports React, Vue, and vanilla JS output.",
    buildLog:
      "Started at Hyderabad Ship-It Sprint. Forms are 80% of web development but they're tedious. Used LLMs to parse natural language descriptions into form schemas, then code-generated the components. The validation generation was surprisingly hard - had to handle edge cases like dependent fields and conditional logic.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://formcraft.ai",
    category: "AI tool",
    event: "e5",
    team: [
      { memberId: "m11", name: "Aditya Joshi", avatar: "", role: "Founder" },
    ],
    weekSubmitted: 6,
    submittedAt: "2026-02-08T11:00:00Z",
    weightedScore: 58,
    rawVotes: 16,
    traction: { users: 89, revenue: "Pre-revenue" },
  },
  {
    _id: "p10",
    name: "DataWeave",
    tagline: "Connect any API to any spreadsheet in 2 clicks",
    description:
      "DataWeave bridges the gap between APIs and spreadsheets. Import data from REST APIs, GraphQL endpoints, or databases directly into Google Sheets or Excel. Set up auto-refresh schedules and transformations.",
    buildLog:
      "Built at Pune Builder Weekend. Data analysts spend hours copying data from APIs to spreadsheets. We built a Google Sheets add-on that lets you connect to any API with a URL and auth token. The transformation layer lets you flatten nested JSON and map fields visually.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://dataweave.tools",
    category: "Internal tool",
    event: "e4",
    team: [
      { memberId: "m12", name: "Nisha Agarwal", avatar: "", role: "Lead" },
      { memberId: "m4", name: "Sneha Iyer", avatar: "", role: "Backend" },
    ],
    weekSubmitted: 3,
    submittedAt: "2026-01-18T14:00:00Z",
    weightedScore: 52,
    rawVotes: 15,
    traction: { users: "210 active users", revenue: "Pre-revenue" },
  },
  {
    _id: "p11",
    name: "GitMentor",
    tagline: "AI code reviewer that teaches as it reviews",
    description:
      "GitMentor is a GitHub App that reviews your PRs with educational explanations. Instead of just pointing out issues, it explains why something is a problem and teaches best practices. Perfect for junior developers and bootcamp grads.",
    buildLog:
      "Built during GrowthX Host Club Bangalore event. The idea came from mentoring junior devs - they need to understand WHY, not just WHAT to fix. Uses GPT-4 to analyze diffs, then generates review comments with explanations, examples, and links to relevant documentation.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://gitmentor.dev",
    category: "Developer tool",
    event: "e7",
    team: [
      { memberId: "m1", name: "Arjun Mehta", avatar: "", role: "Lead" },
      { memberId: "m10", name: "Meera Krishnan", avatar: "", role: "Backend" },
    ],
    weekSubmitted: 4,
    submittedAt: "2026-01-28T10:00:00Z",
    weightedScore: 93,
    rawVotes: 25,
    traction: { users: "890 GitHub installs", revenue: "Pre-revenue" },
  },
  {
    _id: "p12",
    name: "LaunchPad",
    tagline: "Get your first 100 users with automated outreach",
    description:
      "LaunchPad helps early-stage products find their first users through targeted outreach. Identifies potential users on Twitter, Reddit, and HN based on your product description. Generates personalized outreach messages.",
    buildLog:
      "Built this independently after struggling to get users for my own projects. The user identification algorithm scrapes relevant communities and scores potential users based on their interests and pain points. The message generation ensures outreach feels personal, not spammy.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://launchpad.tools",
    category: "SaaS",
    event: undefined,
    team: [
      { memberId: "m11", name: "Aditya Joshi", avatar: "", role: "Solo Founder" },
    ],
    weekSubmitted: 5,
    submittedAt: "2026-01-30T10:00:00Z",
    weightedScore: 48,
    rawVotes: 14,
    traction: { users: 67, revenue: "$560 MRR" },
  },
  {
    _id: "p13",
    name: "PromptVault",
    tagline: "Version control and team sharing for AI prompts",
    description:
      "PromptVault is Git for prompts. Version control your prompts, share them with your team, run A/B tests, and track performance metrics across different LLM providers.",
    buildLog:
      "Built at The Great Indian AI Batch 1 cohort. Everyone is writing prompts but nobody is managing them well. We built a VS Code extension and web app that lets you version prompts, test them across models, and share the best ones. The diff view for prompt changes was surprisingly useful.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://promptvault.dev",
    category: "AI tool",
    event: "e3",
    cohortTag: "The Great Indian AI Batch 1",
    team: [
      { memberId: "m1", name: "Arjun Mehta", avatar: "", role: "Backend" },
      { memberId: "m2", name: "Priya Sharma", avatar: "", role: "Product" },
      { memberId: "m7", name: "Vikram Singh", avatar: "", role: "Infrastructure" },
    ],
    weekSubmitted: 3,
    submittedAt: "2026-01-15T14:00:00Z",
    weightedScore: 104,
    rawVotes: 27,
    traction: { users: "380 users", revenue: "Pre-revenue" },
  },
  {
    _id: "p14",
    name: "APIBridge",
    tagline: "Universal API adapter that translates between any two APIs",
    description:
      "APIBridge sits between your app and third-party APIs, handling authentication, rate limiting, retries, and response transformation. Define mappings once, swap providers without changing your code.",
    buildLog:
      "Built at Hyderabad Ship-It Sprint. We kept rewriting integration code every time we switched providers. APIBridge acts as a middleware layer. Define your ideal API interface, then map it to any provider. When you switch from Stripe to Razorpay, you just update the mapping, not your code.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://apibridge.dev",
    category: "API",
    event: "e5",
    team: [
      { memberId: "m7", name: "Vikram Singh", avatar: "", role: "Architect" },
      { memberId: "m12", name: "Nisha Agarwal", avatar: "", role: "Backend" },
    ],
    weekSubmitted: 6,
    submittedAt: "2026-02-08T14:00:00Z",
    weightedScore: 45,
    rawVotes: 13,
    traction: { users: "150 developers", revenue: "Pre-revenue" },
  },
  {
    _id: "p15",
    name: "ScreenRec",
    tagline: "Instant screen recordings with AI-generated summaries",
    description:
      "ScreenRec captures your screen and generates AI summaries, chapters, and transcripts. Share async video updates with your team. Think Loom but with built-in AI intelligence.",
    buildLog:
      "Built at GrowthX Host Club Bangalore. Async video is powerful but nobody watches full recordings. We added AI that extracts key moments, generates summaries, and creates searchable transcripts. The Chrome extension captures tab + mic. Processing happens server-side with Whisper + GPT-4.",
    logo: "",
    screenshots: [],
    demoVideo: "",
    productUrl: "https://screenrec.app",
    category: "Consumer app",
    event: "e7",
    team: [
      { memberId: "m2", name: "Priya Sharma", avatar: "", role: "Product" },
      { memberId: "m6", name: "Ananya Reddy", avatar: "", role: "Frontend" },
    ],
    weekSubmitted: 4,
    submittedAt: "2026-01-28T14:00:00Z",
    weightedScore: 82,
    rawVotes: 22,
    traction: { users: "670 users", revenue: "$450 MRR" },
  },
];

export const seedVotes: Vote[] = [
  // Votes for ContextPilot (p1) - weightedScore: 142, rawVotes: 38
  { _id: "v1", projectId: "p1", memberId: "m2", role: "builder", weight: 5, createdAt: "2026-02-01T12:00:00Z" },
  { _id: "v2", projectId: "p1", memberId: "m3", role: "host", weight: 4, createdAt: "2026-02-01T12:30:00Z" },
  { _id: "v3", projectId: "p1", memberId: "m4", role: "builder", weight: 5, createdAt: "2026-02-01T13:00:00Z" },
  { _id: "v4", projectId: "p1", memberId: "m5", role: "founder", weight: 3, createdAt: "2026-02-01T13:30:00Z" },
  { _id: "v5", projectId: "p1", memberId: "m7", role: "builder", weight: 5, createdAt: "2026-02-01T14:00:00Z" },
  { _id: "v6", projectId: "p1", memberId: "m10", role: "builder", weight: 5, createdAt: "2026-02-02T10:00:00Z" },
  // Votes for ShipLog (p2)
  { _id: "v7", projectId: "p2", memberId: "m1", role: "builder", weight: 5, createdAt: "2026-02-01T13:00:00Z" },
  { _id: "v8", projectId: "p2", memberId: "m3", role: "host", weight: 4, createdAt: "2026-02-01T14:00:00Z" },
  { _id: "v9", projectId: "p2", memberId: "m5", role: "founder", weight: 3, createdAt: "2026-02-01T15:00:00Z" },
  { _id: "v10", projectId: "p2", memberId: "m6", role: "builder", weight: 5, createdAt: "2026-02-02T10:00:00Z" },
  // Votes for NeuralDocs (p3)
  { _id: "v11", projectId: "p3", memberId: "m1", role: "builder", weight: 5, createdAt: "2026-01-15T12:00:00Z" },
  { _id: "v12", projectId: "p3", memberId: "m2", role: "builder", weight: 5, createdAt: "2026-01-15T13:00:00Z" },
  { _id: "v13", projectId: "p3", memberId: "m5", role: "founder", weight: 3, createdAt: "2026-01-16T10:00:00Z" },
  { _id: "v14", projectId: "p3", memberId: "m10", role: "builder", weight: 5, createdAt: "2026-01-16T11:00:00Z" },
  // Votes for QuickLaunch (p4)
  { _id: "v15", projectId: "p4", memberId: "m1", role: "builder", weight: 5, createdAt: "2026-01-25T14:00:00Z" },
  { _id: "v16", projectId: "p4", memberId: "m2", role: "builder", weight: 5, createdAt: "2026-01-25T15:00:00Z" },
  { _id: "v17", projectId: "p4", memberId: "m4", role: "builder", weight: 5, createdAt: "2026-01-26T10:00:00Z" },
  // Votes for PromptVault (p13)
  { _id: "v18", projectId: "p13", memberId: "m4", role: "builder", weight: 5, createdAt: "2026-01-15T16:00:00Z" },
  { _id: "v19", projectId: "p13", memberId: "m5", role: "founder", weight: 3, createdAt: "2026-01-16T10:00:00Z" },
  { _id: "v20", projectId: "p13", memberId: "m6", role: "builder", weight: 5, createdAt: "2026-01-16T12:00:00Z" },
  { _id: "v21", projectId: "p13", memberId: "m10", role: "builder", weight: 5, createdAt: "2026-01-17T10:00:00Z" },
];

export const seedComments: Comment[] = [
  {
    _id: "c1",
    projectId: "p1",
    memberId: "m2",
    memberName: "Priya Sharma",
    memberAvatar: "",
    content: "This is exactly what I needed. The context awareness is leagues ahead of Copilot for large codebases.",
    createdAt: "2026-02-01T14:00:00Z",
  },
  {
    _id: "c2",
    projectId: "p1",
    memberId: "m5",
    memberName: "Karan Patel",
    memberAvatar: "",
    content: "Tried it on our monorepo - handles the cross-package references really well. How are you handling incremental indexing?",
    createdAt: "2026-02-01T16:00:00Z",
  },
  {
    _id: "c3",
    projectId: "p1",
    memberId: "m1",
    memberName: "Arjun Mehta",
    memberAvatar: "",
    content: "Thanks! We use file watchers + git hooks for incremental updates. Full re-index only needed when you switch branches significantly.",
    parentId: "c2",
    createdAt: "2026-02-01T17:00:00Z",
  },
  {
    _id: "c4",
    projectId: "p2",
    memberId: "m1",
    memberName: "Arjun Mehta",
    memberAvatar: "",
    content: "Love the Twitter thread generator. Would be great to add LinkedIn support too.",
    createdAt: "2026-02-02T10:00:00Z",
  },
  {
    _id: "c5",
    projectId: "p3",
    memberId: "m7",
    memberName: "Vikram Singh",
    memberAvatar: "",
    content: "We deployed this for our internal docs. The Slack bot is a game changer - people actually find answers now.",
    createdAt: "2026-01-16T10:00:00Z",
  },
  {
    _id: "c6",
    projectId: "p4",
    memberId: "m6",
    memberName: "Ananya Reddy",
    memberAvatar: "",
    content: "The generated landing pages are surprisingly good. The AI copy could use some fine-tuning for non-English markets though.",
    createdAt: "2026-01-26T14:00:00Z",
  },
  {
    _id: "c7",
    projectId: "p11",
    memberId: "m4",
    memberName: "Sneha Iyer",
    memberAvatar: "",
    content: "This is brilliant for onboarding junior devs. The explanations are clear and educational without being condescending.",
    createdAt: "2026-01-28T16:00:00Z",
  },
  {
    _id: "c8",
    projectId: "p7",
    memberId: "m1",
    memberName: "Arjun Mehta",
    memberAvatar: "",
    content: "Finally a proper alternative to Carbon! The keyboard shortcut workflow is so much faster.",
    createdAt: "2026-01-21T10:00:00Z",
  },
];
